In [2]:
import sys
from pathlib import Path

# Add src/ to the Python path
sys.path.append(str(Path().resolve() / "src"))
sys.path.append(str(Path().resolve() / "data"))


In [ ]:
'''    def resolve_drugs(self) -> None:
        """
        Removes the effects of any Addictions if their respective Drug
        is already administered.
        """
        removal_necessary: bool = False

        for affect in self.modifier_list:
            
            if affect+"_addiction" in self.modifier_list:
                print(affect+"_addiction")
                removal_necessary = True
                break
            else:
                print(f"{affect+"_addiction"} not in {self.modifier_list}")
        
        if removal_necessary:
            for affect in self.data.keys():
                self.data[affect] = [t for t in self.data[affect] if (not t[0].endswith("_addiction")
                                        or t[0][:-10] not in self.modifier_list)]
                print(f"FROM inside {self.data[affect]}")

        self.modifier_list = [s for s in self.modifier_list if not s.endswith("_addiction")]'''
        
                

In [2]:

#DV Clear Chance

import numpy as np
from collections import Counter

In [3]:
import numpy as np
import pandas as pd

black_ice = pd.read_csv(r"data\black_ice.csv")
programs = pd.read_csv(r"data\programs.csv")

combined = pd.concat([black_ice, programs])
combined["name"].values

array(['Asp', 'Giant', 'Hellhound', 'Kraken', 'Liche', 'Raven',
       'Scorpion', 'Skunk', 'Wisp', 'Dragon', 'Killer', 'Sabertooth',
       'Eraser', 'See Ya', 'Speedy Gonzalvez', 'Worm', 'Armor', 'Flak',
       'Shield', 'Banhammer', 'Sword', 'DeckKRASH', 'Hellbolt',
       'Nervescrub', 'Poison Flatline', 'Superglue', 'Vrizzbolt'],
      dtype=object)

<h1>Testing the Check</h1>


In [10]:
from cyberpunk.dice import roll_dice
from cyberpunk.check import Check

my_dice = roll_dice([-10], modifiers=[4])
opponent_dice = roll_dice([-10], modifiers=[0]) * -1

my_check = Check([my_dice, opponent_dice], ties_count=False)

print(my_check)
print(my_check.full_stats(key_values=list(range(8)), use_thresholds=True))

DV  : 0
PASS: 73.18% | FAIL: 26.82%

FAIL  26.82%
   0  77.90%
   1  73.18%
   2  67.64%
   3  61.28%
   4  54.10%
   5  45.90%
   6  38.72%
   7  32.36%
   9  22.10%
  14  9.80%
  18  3.94%
  22  0.92%


<h1>Using Black Ice/Netrunners from File</h1>

In [5]:
import os
print(os.path.exists(r"data\netrunners.json"))

True


In [6]:

try:
    netrunners = pd.read_json(r"data\netrunners.json")
    print(netrunners)
except:
    print("No netrunner file")

       hp  interface programs
Aphex  69          4       {}


In [7]:
from cyberpunk.netrunner import Netrunner

aphex = Netrunner("Aphex", hp=69, interface=4)
print(aphex)

AttributeError: 'Netrunner' object has no attribute '_programs'

In [ ]:
aphex.save()

In [ ]:
aphex_again = Netrunner("Aphex")
print(aphex)

{'name': 'Aphex', 'hp': 69, 'interface': 4, 'programs': {}}


In [ ]:
import pandas as pd
from cyberpunk.black_ice import BlackIce

black_ice = pd.read_csv(r"data\black_ice.csv")
black_ice

name                     class  perception  speed  attack  defense  \
0          Asp  Anti-Personnel Black ICE           4      6       2        2   
1        Giant  Anti-Personnel Black ICE           2      2       8        4   
2    Hellhound  Anti-Personnel Black ICE           6      6       6        2   
3       Kraken  Anti-Personnel Black ICE           6      2       8        4   
4        Liche  Anti-Personnel Black ICE           8      2       6        2   
5        Raven  Anti-Personnel Black ICE           6      4       4        2   
6     Scorpion  Anti-Personnel Black ICE           2      6       2        2   
7        Skunk  Anti-Personnel Black ICE           2      4       4        2   
8         Wisp  Anti-Personnel Black ICE           4      4       4        2   
9       Dragon    Anti-Program Black ICE           6      4       6        6   
10      Killer    Anti-Program Black ICE           4      8       6        2   
11  Sabertooth    Anti-Program Black ICE           8      6       6        2   

    rez                                             effect dice  
0    15  Destroys a single Program installed on the ene...  NaN  
1    25  Does 3d6 damage direct to an enemy Netrunner's...  3d6  
2    20  Does 2d6 damage direct to the Netrunner's brai...  2d6  
3    30  Does 3d6 damage direct to an enemy Netrunner's...  3d6  
4    25  Enemy Netrunner's INT, REF, and DEX are each l...  NaN  
5    15  Derezzes a single Defender Program the enemy N...  1d6  
6    15  Enemy Netrunner's MOVE is lowered by 1d6 for t...  1d6  
7    10  Until this Program is Derezzed, an enemy Netru...  NaN  
8    15  Does 1d6 damage direct to the enemy Netrunner'...  1d6  
9    30  Deals 6d6 damage to a Program. If this damage ...  6d6  
10   20  Deals 4d6 damage to a Program. If this damage ...  4d6  
11   25  Deals 6d6 damage to a Program. If this damage ...  6d6

In [ ]:
my_black_ice = BlackIce("Kraken")
print(my_black_ice)

Kraken - Anti-Personnel, 8 + 3d6
PER SPD ATK DEF REZ
 6   2   8   4  30 



In [ ]:
from cyberpunk.dv_check import *

calculate_DV_pass(DV=10, dice=[-10], modifiers=[4,2])

Possible Rolls:
[[ 6  8  9 10 11 12 13 14 15 17]
 [ 5  8  9 10 11 12 13 14 15 18]
 [ 4  8  9 10 11 12 13 14 15 19]
 [ 3  8  9 10 11 12 13 14 15 20]
 [ 2  8  9 10 11 12 13 14 15 21]
 [ 1  8  9 10 11 12 13 14 15 22]
 [ 0  8  9 10 11 12 13 14 15 23]
 [-1  8  9 10 11 12 13 14 15 24]
 [-2  8  9 10 11 12 13 14 15 25]
 [-3  8  9 10 11 12 13 14 15 26]]
DV: 10
Chance of Success: 65.93%
Chance of Success w/ Ties: 67.03%


In [ ]:
def roll_against_opponent_and_DV(DV:int, rolls:list):
    
    possibilities = np.array(0)

    for roll in rolls:
        possibilities = np.add.outer(possibilities, roll)

    output_dice_tensor(possibilities)
    output_check_success_odds(possibilities, DV)
        

your_roll = roll_dice(dice=[-10], modifiers=[4])
opponent_roll = roll_dice(dice=[10], modifiers=[2]) * -1

roll_against_opponent_and_DV(DV=0, rolls=[your_roll, opponent_roll])

rolls.shape: (10, 10, 10)
DV: 0
Chance of Success: 62.10%
Chance of Success w/ Ties: 69.30%


In [ ]:
sword = roll_dice(dice=[-10, 6, 6, 6], modifiers=[4])
zap = roll_dice(dice=[-10, 6], modifiers=[4])

print("Sword + Sword")
takedown_odds(attacks=[sword, sword], DEF=2)

print("\n Sword + Zap + Zap")
takedown_odds(attacks=[sword, zap, zap], DEF=2)

Sword + Sword
DMG: 54   Odds: 1.24%
DMG: 48   Odds: 5.46%
DMG: 44   Odds: 11.92%
DMG: 39   Odds: 27.73%
DMG: 37   Odds: 36.97%
DMG: 34   Odds: 52.67%
DMG: 31   Odds: 67.84%
DMG: 29   Odds: 76.30%
DMG: 24   Odds: 90.13%
DMG: 20   Odds: 95.70%
DMG: 14   Odds: 99.16%
Sum of probabilities = 1.0

 Sword + Zap + Zap
DMG: 57   Odds: 1.18%
DMG: 50   Odds: 5.46%
DMG: 46   Odds: 11.15%
DMG: 40   Odds: 27.06%
DMG: 38   Odds: 34.80%
DMG: 34   Odds: 52.77%
DMG: 31   Odds: 66.23%
DMG: 28   Odds: 77.68%
DMG: 23   Odds: 90.64%
DMG: 20   Odds: 95.08%
DMG: 13   Odds: 99.24%
Sum of probabilities = 1.0


In [ ]:

hellhound = roll_dice(dice=[6,6], modifiers=[6])
wisp = roll_dice(dice=[6], modifiers=[4])
kraken = roll_dice(dice=[6,6,6], modifiers=[8])

level_four_netrunner = roll_dice(dice=[10], modifiers=[4])
attacks = [kraken] + [hellhound]*2 + [wisp] 

print("Kraken, Hellhoundx2, Wisp vs. Level 4 Netrunner")
takedown_odds(attacks=attacks, DEF=level_four_netrunner, REZ=40)

Kraken, Hellhoundx2, Wisp vs. Level 4 Netrunner
DMG: 40   Odds: 0.02%
DMG: 32   Odds: 1.37%
DMG: 28   Odds: 5.65%
DMG: 26   Odds: 10.02%
DMG: 22   Odds: 25.06%
DMG: 20   Odds: 35.66%
DMG: 17   Odds: 53.85%
DMG: 15   Odds: 66.02%
DMG: 13   Odds: 76.95%
DMG:  9   Odds: 92.25%
DMG:  7   Odds: 96.35%
DMG:  4   Odds: 99.21%
Sum of probabilities = 0.9999999999999999


In [ ]:

my_defense = roll_dice([-10], [4])
my_defense[my_defense < 0] = 0

takedown_odds(attacks=[hellhound, kraken], REZ=40, DEF=my_defense)

DMG: 40   Odds: 0.01%
DMG: 30   Odds: 1.04%
DMG: 25   Odds: 5.04%
DMG: 22   Odds: 10.82%
DMG: 17   Odds: 29.44%
DMG: 16   Odds: 34.67%
DMG: 13   Odds: 52.58%
DMG: 10   Odds: 70.91%
DMG:  9   Odds: 76.34%
DMG:  5   Odds: 91.88%
DMG:  3   Odds: 95.94%
DMG:  0   Odds: 100.00%
Sum of probabilities = 1.0


In [ ]:
aphex = Netrunner(hp=40, interface=4)
takedown_odds(attacks=[hellhound, kraken], netrunner=aphex)

TypeError: Netrunner.__init__() missing 1 required positional argument: 'name'

In [1]:
list(range(1, 36, 5)) + [35]

[1, 6, 11, 16, 21, 26, 31, 35]

In [ ]:
import clipboard

def copy_damage_roll(dice:str, weapon:str):
    
    amount, sides = dice.split("d")
    discord_command = f"!r {amount}d{sides} Damage w/ {weapon}"
    clipboard.copy(discord_command)

copy_damage_roll("3d6", "Stungun")


In [16]:
import pandas as pd

df = pd.read_csv(r"data\weapons.csv")
df

name             type quality  modifier  \
0                     Air Pistol    Medium Pistol     NaN       NaN   
1          Dai Lung Streetmaster    Medium Pistol     NaN       NaN   
2                    Duel Caster    Medium Pistol     NaN       NaN   
3           Federated Arms X-9mm    Medium Pistol     NaN       NaN   
4                  Medium Pistol    Medium Pistol     NaN       NaN   
..                           ...              ...     ...       ...   
228      Militech Hotshot L-ATGM  Rocket Launcher      EQ       NaN   
229   Militech Starshot L-ATGM-N  Rocket Launcher      EQ       NaN   
230               Militech Urban  Rocket Launcher      SQ       NaN   
231    Towa Manufacturing Type-R  Rocket Launcher      PQ       NaN   
232  Towa Manufacturing Type-R*2  Rocket Launcher      SQ       NaN   

                  source  banned  
0               CP:R 347     NaN  
1               CP:R 342     NaN  
2    DL:ElfTCG 9, IR3 73     NaN  
3               CP:R 342     NaN  
4               CP:R 341     NaN  
..                   ...     ...  
228                TT 25     NaN  
229                TT 25     NaN  
230                TT 25     NaN  
231                TT 25     NaN  
232                TT 25     NaN  

[233 rows x 6 columns]

In [1]:
magnitudes = [-5,3,1,3,-8,0,-1]
nums = []

for num in magnitudes:
    if num >= 0:
        nums.append(f"+{num}")
    else:
        nums.append(f"{num}")

print("".join(nums))

-5+3+1+3-8+0-1


In [30]:
weapon = "Arasaka Ozere"
weapons_list = pd.read_csv(r"data\weapons.csv")

#print(weapons_list["type"].unique())

for i in range(len(weapon)):
    weapons_list = weapons_list[ 
        weapons_list["name"].str.contains(weapon[:i+1], na=False)
    ]
    if len(weapons_list) <= 1:
        break



weapons_list['type'].iloc[0]

'Bow'